# .github/workflows/features.yml
name: Test and Integrate Features

run-name: Test the Application and Create a Pull Request

on:
    push:
        branches:
            - 'feature/**'

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run tests
              run: pytest

    PR:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Create Pull Request
              run: gh pr create -B dev -H ${{github.ref_name}} --title "Merge branch ${{ github.ref_name}} into dev" --body "Created by Github Action"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}